services:

  backend:
    build: .
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:800"    
    volumes:
      - .:/backend
    ports:
      - "800:800"
    networks:
      drf_nw:
        ipv4_address: 172.20.0.2
      mamamia:
        ipv4_address: 172.23.0.2
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres
    networks:
      drf_nw:
        ipv4_address: 172.20.0.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


networks:
  mamamia:
    name: "backend_mamamia"
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"

  drf_nw:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"


  