# Generated by Django 4.0.8 on 2023-02-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
